swagger: "2.0"
info:
  title: API Gateway Service
  description: Node JS, Typescript and JWT
  version: 1.0.0
host: api.evgeniy.poznyaks.com
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
  - http
paths:
  /skills:
    get:
      summary: Returns a list of skills.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
